### ISSUE TITLE
No ARTCC Data

### ISSUE THREAD

**Issue by mgateno** [SuperCheese21/vatscan-react-native#22]
The app now shows flights but I get an error message that says "Unable to fetch ARTCC data"

**Comment by Stracenzo** [comment]
Besides the unable to fetch ARTCC data, still  I have 0 Clients on the top left corner.

**Comment by mgateno** [comment]
I don't. Mine shows the actual number of clients. Try flushing your Storage Cache

**Comment by Stracenzo** [comment]
On a fresh download?

**Comment by Stracenzo** [comment]
Nope... cleared the cache, O Clients

**Comment by SuperCheese21** [comment]
> Besides the unable to fetch ARTCC data, still I have 0 Clients on the top left corner.

I pushed an update that fixes that bug. Have you tried re-downloading from the Play Store?

**Comment by mgateno** [comment]
I have the latest version. The problem persists. I can see Tower Ground and
Departure but not the Area controllers. No ARTCC area limits show on the
map.

The error message still appears.

**Comment by mgateno** [comment]
I thought I was responding to the other issue I opened. I don't have an issue with number of clients. Just ARTCC.

**Comment by Stracenzo** [comment]
https://github.com/SuperCheese21/vatscan/issues/22#issuecomment-536272284

Now I'm able to see the Clients (754) from GND to APP but not ARTCC

**Comment by Stracenzo** [comment]
No errors this morning and now I'm able to see the ARTCC as well.... thanks!!!

**Comment by mgateno** [comment]
Same here. I believe we are good to go

**Comment by mgateno** [comment]
Tonight again I'm getting no ARTCC data

**Comment by mgateno** [comment]
I'm able to see the ARTCC data again but it does not show the ARTCC identifier in the map as before

**Comment by SuperCheese21** [comment]
Unfortunately, this issue is due to an external API being unavailable. I am looking into another data source for ARTCC boundaries but for now my focuses are on other areas of the app.
